/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Josué Graão
 */
public class Cliente_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Cliente_GUI
     */
    public Cliente_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Voltar = new javax.swing.JButton();
        nomeLabel = new javax.swing.JLabel();
        nomeTF = new javax.swing.JTextField();
        cpfLabel = new javax.swing.JLabel();
        cpfTF = new javax.swing.JTextField();
        rgLabel = new javax.swing.JLabel();
        rgTF = new javax.swing.JTextField();
        nascLabel = new javax.swing.JLabel();
        nascTF = new javax.swing.JTextField();
        contLabel = new javax.swing.JLabel();
        celLabel = new javax.swing.JLabel();
        celTF = new javax.swing.JTextField();
        resiLabel = new javax.swing.JLabel();
        resiTF = new javax.swing.JTextField();
        mailLabel = new javax.swing.JLabel();
        mailTF = new javax.swing.JTextField();
        iconLabel = new javax.swing.JLabel();
        petsLabel = new javax.swing.JLabel();
        p1Label = new javax.swing.JLabel();
        pnomeLabel = new javax.swing.JLabel();
        pnomeTF = new javax.swing.JTextField();
        rLabel = new javax.swing.JLabel();
        rTF = new javax.swing.JTextField();
        p2Label = new javax.swing.JLabel();
        pnome2Label = new javax.swing.JLabel();
        pnome2TF = new javax.swing.JTextField();
        r2Label = new javax.swing.JLabel();
        r2TF = new javax.swing.JTextField();
        p3Label = new javax.swing.JLabel();
        pnome3Label = new javax.swing.JLabel();
        pnome3TF = new javax.swing.JTextField();
        r3Label = new javax.swing.JLabel();
        r3TF = new javax.swing.JTextField();
        p4Label = new javax.swing.JLabel();
        pnome4Label = new javax.swing.JLabel();
        pnome4TF = new javax.swing.JTextField();
        r4Label = new javax.swing.JLabel();
        r4TF = new javax.swing.JTextField();
        p5Label = new javax.swing.JLabel();
        pnome5Label = new javax.swing.JLabel();
        pnome5TF = new javax.swing.JTextField();
        r5Label = new javax.swing.JLabel();
        r5TF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel2.setLayout(null);

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        jPanel2.add(Voltar);
        Voltar.setBounds(400, 450, 77, 32);

        nomeLabel.setForeground(new java.awt.Color(0, 0, 0));
        nomeLabel.setText("Nome");
        jPanel2.add(nomeLabel);
        nomeLabel.setBounds(240, 20, 60, 20);

        nomeTF.setToolTipText("Digite o nome completo do cliente");
        nomeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTFActionPerformed(evt);
            }
        });
        jPanel2.add(nomeTF);
        nomeTF.setBounds(240, 40, 600, 24);

        cpfLabel.setForeground(new java.awt.Color(0, 0, 0));
        cpfLabel.setText("CPF");
        jPanel2.add(cpfLabel);
        cpfLabel.setBounds(240, 70, 60, 16);

        cpfTF.setToolTipText("Digite o CPF do cliente");
        jPanel2.add(cpfTF);
        cpfTF.setBounds(240, 90, 180, 24);

        rgLabel.setForeground(new java.awt.Color(51, 51, 51));
        rgLabel.setText("RG");
        jPanel2.add(rgLabel);
        rgLabel.setBounds(450, 70, 30, 20);

        rgTF.setToolTipText("Digite o RG do cliente");
        rgTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgTFActionPerformed(evt);
            }
        });
        jPanel2.add(rgTF);
        rgTF.setBounds(450, 90, 180, 24);

        nascLabel.setForeground(new java.awt.Color(0, 0, 0));
        nascLabel.setText("Data de Nascimento");
        jPanel2.add(nascLabel);
        nascLabel.setBounds(660, 70, 130, 16);

        nascTF.setToolTipText("Digite a data de nascimento do cliente");
        nascTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nascTFActionPerformed(evt);
            }
        });
        jPanel2.add(nascTF);
        nascTF.setBounds(660, 90, 180, 24);

        contLabel.setForeground(new java.awt.Color(0, 0, 0));
        contLabel.setText("Contatos");
        jPanel2.add(contLabel);
        contLabel.setBounds(240, 130, 90, 16);

        celLabel.setForeground(new java.awt.Color(0, 0, 0));
        celLabel.setText("Celular");
        jPanel2.add(celLabel);
        celLabel.setBounds(240, 160, 80, 16);

        celTF.setToolTipText("Digite o número do celular do cliente");
        celTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celTFActionPerformed(evt);
            }
        });
        jPanel2.add(celTF);
        celTF.setBounds(240, 180, 180, 24);

        resiLabel.setForeground(new java.awt.Color(0, 0, 0));
        resiLabel.setText("Residência");
        jPanel2.add(resiLabel);
        resiLabel.setBounds(450, 160, 80, 16);

        resiTF.setToolTipText("Digite o número residencial do cliente");
        jPanel2.add(resiTF);
        resiTF.setBounds(450, 180, 180, 24);

        mailLabel.setForeground(new java.awt.Color(0, 0, 0));
        mailLabel.setText("Email");
        jPanel2.add(mailLabel);
        mailLabel.setBounds(660, 160, 80, 16);

        mailTF.setToolTipText("Digite o email do cliente");
        jPanel2.add(mailTF);
        mailTF.setBounds(660, 180, 180, 24);

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/person.png"))); // NOI18N
        jPanel2.add(iconLabel);
        iconLabel.setBounds(60, 40, 128, 150);

        petsLabel.setForeground(new java.awt.Color(0, 0, 0));
        petsLabel.setText("Pets");
        jPanel2.add(petsLabel);
        petsLabel.setBounds(70, 230, 50, 16);

        p1Label.setForeground(new java.awt.Color(0, 0, 0));
        p1Label.setText("Pet 1");
        jPanel2.add(p1Label);
        p1Label.setBounds(70, 260, 70, 16);

        pnomeLabel.setForeground(new java.awt.Color(0, 0, 0));
        pnomeLabel.setText("Nome");
        jPanel2.add(pnomeLabel);
        pnomeLabel.setBounds(70, 290, 70, 16);
        jPanel2.add(pnomeTF);
        pnomeTF.setBounds(70, 320, 120, 24);

        rLabel.setForeground(new java.awt.Color(0, 0, 0));
        rLabel.setText("Raça");
        jPanel2.add(rLabel);
        rLabel.setBounds(70, 360, 70, 16);
        jPanel2.add(rTF);
        rTF.setBounds(70, 390, 120, 24);

        p2Label.setForeground(new java.awt.Color(0, 0, 0));
        p2Label.setText("Pet 2");
        jPanel2.add(p2Label);
        p2Label.setBounds(240, 260, 60, 16);

        pnome2Label.setForeground(new java.awt.Color(0, 0, 0));
        pnome2Label.setText("Nome");
        jPanel2.add(pnome2Label);
        pnome2Label.setBounds(240, 290, 80, 16);
        jPanel2.add(pnome2TF);
        pnome2TF.setBounds(240, 320, 120, 24);

        r2Label.setForeground(new java.awt.Color(0, 0, 0));
        r2Label.setText("Raça");
        jPanel2.add(r2Label);
        r2Label.setBounds(240, 360, 70, 16);
        jPanel2.add(r2TF);
        r2TF.setBounds(240, 390, 120, 24);

        p3Label.setForeground(new java.awt.Color(0, 0, 0));
        p3Label.setText("Pet 3");
        jPanel2.add(p3Label);
        p3Label.setBounds(410, 260, 70, 16);

        pnome3Label.setForeground(new java.awt.Color(0, 0, 0));
        pnome3Label.setText("Nome");
        jPanel2.add(pnome3Label);
        pnome3Label.setBounds(410, 290, 80, 16);
        jPanel2.add(pnome3TF);
        pnome3TF.setBounds(410, 320, 120, 24);

        r3Label.setForeground(new java.awt.Color(0, 0, 0));
        r3Label.setText("Raça");
        jPanel2.add(r3Label);
        r3Label.setBounds(410, 360, 80, 16);
        jPanel2.add(r3TF);
        r3TF.setBounds(410, 390, 120, 24);

        p4Label.setForeground(new java.awt.Color(0, 0, 0));
        p4Label.setText("Pet 4");
        jPanel2.add(p4Label);
        p4Label.setBounds(570, 260, 80, 16);

        pnome4Label.setForeground(new java.awt.Color(0, 0, 0));
        pnome4Label.setText("Nome");
        jPanel2.add(pnome4Label);
        pnome4Label.setBounds(570, 290, 80, 16);
        jPanel2.add(pnome4TF);
        pnome4TF.setBounds(570, 320, 120, 24);

        r4Label.setForeground(new java.awt.Color(0, 0, 0));
        r4Label.setText("Raça");
        jPanel2.add(r4Label);
        r4Label.setBounds(570, 360, 90, 16);
        jPanel2.add(r4TF);
        r4TF.setBounds(570, 390, 120, 24);

        p5Label.setForeground(new java.awt.Color(0, 0, 0));
        p5Label.setText("Pet 5");
        jPanel2.add(p5Label);
        p5Label.setBounds(720, 260, 80, 16);

        pnome5Label.setForeground(new java.awt.Color(0, 0, 0));
        pnome5Label.setText("Nome");
        jPanel2.add(pnome5Label);
        pnome5Label.setBounds(720, 290, 80, 16);
        jPanel2.add(pnome5TF);
        pnome5TF.setBounds(720, 320, 120, 24);

        r5Label.setForeground(new java.awt.Color(0, 0, 0));
        r5Label.setText("Raça");
        jPanel2.add(r5Label);
        r5Label.setBounds(720, 360, 70, 16);
        jPanel2.add(r5TF);
        r5TF.setBounds(720, 390, 120, 24);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 900, 500);

        setSize(new java.awt.Dimension(900, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
        new AInicio_GUI().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void nomeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTFActionPerformed

    private void rgTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgTFActionPerformed

    private void celTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celTFActionPerformed

    private void nascTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nascTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nascTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel celLabel;
    private javax.swing.JTextField celTF;
    private javax.swing.JLabel contLabel;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField cpfTF;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JTextField mailTF;
    private javax.swing.JLabel nascLabel;
    private javax.swing.JTextField nascTF;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTF;
    private javax.swing.JLabel p1Label;
    private javax.swing.JLabel p2Label;
    private javax.swing.JLabel p3Label;
    private javax.swing.JLabel p4Label;
    private javax.swing.JLabel p5Label;
    private javax.swing.JLabel petsLabel;
    private javax.swing.JLabel pnome2Label;
    private javax.swing.JTextField pnome2TF;
    private javax.swing.JLabel pnome3Label;
    private javax.swing.JTextField pnome3TF;
    private javax.swing.JLabel pnome4Label;
    private javax.swing.JTextField pnome4TF;
    private javax.swing.JLabel pnome5Label;
    private javax.swing.JTextField pnome5TF;
    private javax.swing.JLabel pnomeLabel;
    private javax.swing.JTextField pnomeTF;
    private javax.swing.JLabel r2Label;
    private javax.swing.JTextField r2TF;
    private javax.swing.JLabel r3Label;
    private javax.swing.JTextField r3TF;
    private javax.swing.JLabel r4Label;
    private javax.swing.JTextField r4TF;
    private javax.swing.JLabel r5Label;
    private javax.swing.JTextField r5TF;
    private javax.swing.JLabel rLabel;
    private javax.swing.JTextField rTF;
    private javax.swing.JLabel resiLabel;
    private javax.swing.JTextField resiTF;
    private javax.swing.JLabel rgLabel;
    private javax.swing.JTextField rgTF;
    // End of variables declaration//GEN-END:variables
}
