/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Laboratorio-Info
 */
public class Pet_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Pet_GUI
     */
    public Pet_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();
        dogIcon = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        nomeTF = new javax.swing.JTextField();
        nomedLabel = new javax.swing.JLabel();
        nomedTF = new javax.swing.JTextField();
        datarLabel = new javax.swing.JLabel();
        datarTF = new javax.swing.JTextField();
        sexoLabel = new javax.swing.JLabel();
        sexoTF = new javax.swing.JTextField();
        datanLabel = new javax.swing.JLabel();
        datanTF = new javax.swing.JTextField();
        pesoLabel = new javax.swing.JLabel();
        pesoTF = new javax.swing.JTextField();
        espLabel = new javax.swing.JLabel();
        espTF = new javax.swing.JTextField();
        raçaLabel = new javax.swing.JLabel();
        raçaTF = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        vacLabel = new javax.swing.JLabel();
        vacTF = new javax.swing.JTextField();
        infoLabel = new javax.swing.JLabel();
        infoTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro do Pet", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(null);

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel2.add(voltar);
        voltar.setBounds(420, 430, 100, 32);

        dogIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dog.png"))); // NOI18N
        jPanel2.add(dogIcon);
        dogIcon.setBounds(70, 50, 130, 120);

        nomeLabel.setForeground(new java.awt.Color(0, 0, 0));
        nomeLabel.setText("Nome");
        jPanel2.add(nomeLabel);
        nomeLabel.setBounds(250, 50, 60, 16);

        nomeTF.setToolTipText("Digite o nome do animal");
        jPanel2.add(nomeTF);
        nomeTF.setBounds(250, 70, 120, 24);

        nomedLabel.setForeground(new java.awt.Color(0, 0, 0));
        nomedLabel.setText("Nome do dono");
        jPanel2.add(nomedLabel);
        nomedLabel.setBounds(390, 50, 110, 16);

        nomedTF.setToolTipText("Digite o nome do dono");
        jPanel2.add(nomedTF);
        nomedTF.setBounds(390, 70, 280, 24);

        datarLabel.setForeground(new java.awt.Color(0, 0, 0));
        datarLabel.setText("Data de Registro");
        jPanel2.add(datarLabel);
        datarLabel.setBounds(690, 50, 120, 16);

        datarTF.setToolTipText("Digite a data em que o registro está sendo feito");
        jPanel2.add(datarTF);
        datarTF.setBounds(690, 70, 160, 24);

        sexoLabel.setForeground(new java.awt.Color(0, 0, 0));
        sexoLabel.setText("Sexo");
        jPanel2.add(sexoLabel);
        sexoLabel.setBounds(250, 110, 70, 16);

        sexoTF.setToolTipText("Digite o sexo do animal");
        jPanel2.add(sexoTF);
        sexoTF.setBounds(250, 130, 120, 24);

        datanLabel.setForeground(new java.awt.Color(0, 0, 0));
        datanLabel.setText("Data de Nascimento");
        jPanel2.add(datanLabel);
        datanLabel.setBounds(390, 110, 130, 16);

        datanTF.setToolTipText("Digite a data de nascimento do animal");
        jPanel2.add(datanTF);
        datanTF.setBounds(390, 130, 120, 24);

        pesoLabel.setForeground(new java.awt.Color(0, 0, 0));
        pesoLabel.setText("Peso");
        jPanel2.add(pesoLabel);
        pesoLabel.setBounds(530, 110, 70, 16);

        pesoTF.setToolTipText("Digite o peso do animal");
        jPanel2.add(pesoTF);
        pesoTF.setBounds(530, 130, 120, 24);

        espLabel.setForeground(new java.awt.Color(0, 0, 0));
        espLabel.setText("Espécie");
        jPanel2.add(espLabel);
        espLabel.setBounds(670, 110, 80, 16);

        espTF.setToolTipText("Digite a espécie do animal");
        jPanel2.add(espTF);
        espTF.setBounds(670, 130, 180, 24);

        raçaLabel.setForeground(new java.awt.Color(0, 0, 0));
        raçaLabel.setText("Raça");
        jPanel2.add(raçaLabel);
        raçaLabel.setBounds(70, 190, 70, 16);

        raçaTF.setToolTipText("Digite a raça do animal");
        jPanel2.add(raçaTF);
        raçaTF.setBounds(70, 210, 150, 24);

        idLabel.setForeground(new java.awt.Color(0, 0, 0));
        idLabel.setText("Identificação, cor ou pelagem");
        jPanel2.add(idLabel);
        idLabel.setBounds(240, 190, 210, 16);

        idTF.setToolTipText("Digite características que facilitam a identificação do animal");
        jPanel2.add(idTF);
        idTF.setBounds(240, 210, 210, 24);

        vacLabel.setForeground(new java.awt.Color(0, 0, 0));
        vacLabel.setText("Vacinas");
        jPanel2.add(vacLabel);
        vacLabel.setBounds(470, 190, 80, 16);

        vacTF.setToolTipText("Digite as vacinas que o animal já tomou");
        jPanel2.add(vacTF);
        vacTF.setBounds(470, 210, 380, 24);

        infoLabel.setForeground(new java.awt.Color(0, 0, 0));
        infoLabel.setText("Informações sobre o animal");
        jPanel2.add(infoLabel);
        infoLabel.setBounds(70, 250, 220, 16);

        infoTF.setToolTipText("Digite informações adicionais sobre o animal");
        jPanel2.add(infoTF);
        infoTF.setBounds(70, 270, 780, 130);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 900, 500);

        setSize(new java.awt.Dimension(900, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        dispose();
        new AInicio_GUI().setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pet_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pet_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pet_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pet_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pet_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datanLabel;
    private javax.swing.JTextField datanTF;
    private javax.swing.JLabel datarLabel;
    private javax.swing.JTextField datarTF;
    private javax.swing.JLabel dogIcon;
    private javax.swing.JLabel espLabel;
    private javax.swing.JTextField espTF;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JTextField infoTF;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTF;
    private javax.swing.JLabel nomedLabel;
    private javax.swing.JTextField nomedTF;
    private javax.swing.JLabel pesoLabel;
    private javax.swing.JTextField pesoTF;
    private javax.swing.JLabel raçaLabel;
    private javax.swing.JTextField raçaTF;
    private javax.swing.JLabel sexoLabel;
    private javax.swing.JTextField sexoTF;
    private javax.swing.JLabel vacLabel;
    private javax.swing.JTextField vacTF;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
